export const labels = {
    booksPointer: "বুকস পয়েন্টার",
    search: "খুঁজুন...",
    editProfile: "আপডেট প্রোফাইল",
    resetPassword: "রিসেট পাসওয়ার্ড",
    register: "রেজিস্টার করুন",
    noAccount: "একাউন্ট নেই?",
    invalidEmail: "ইমেইলটি সঠিক হয়নি। সঠিক ইমেইল দিয়ে আবার চেষ্টা করুন।",
    passswordConfirmNotMatch: "পাসওয়ার্ড আর কনফার্ম পাসওয়ার্ডে মিল নেই।",
    signIn: "লগইন",
    signOut: "লগআউট",
    editBook: "আপডেট করুন",
    privateBook: "প্রাইভেট করুন",
    publishBook: "পাবলিশ করুন",
    userRoleUser: "ব্যাবহারকারী",
    userRoleAuthor: "লেখক",
    userRolePublisher: "পাবলিশার",
    userBookTypes: {
        books: "বইসমূহ",
        library: "লাইব্রেরী",
    },
    writeBook: "বই লিখুন",
    home: 'হোম', 
    authors: 'লেখকগণ', 
    categories: 'ধরণ', 
    download: 'ডাউনলোড',
    bookCreate: {
        coverMessage: 'আপনি চাইলে একটি ছবিও যুক্ত করতে পারেন বইটির প্রচ্ছদ এর জন্য। (না দিলেও অসুবিধা নেই।)',
        title: 'বইটির নাম', 
        category: 'বইটির ধরণ',
        author: 'বইটির লেখক',
        mainContent: 'মূল লেখা...',
        writeComplete: "লেখা সম্পন্ন হয়েছে।",
        bookExists: "বইটি ইতোমধ্যে বুকস পয়েন্টারে আছে।"
    },
    saveBookIntoDb: "বইটি সফলভাবে সেভ হয়েছে।",
    saveBookIntoLibrary: "বইটি সফলভাবে লাইব্রেরীতে যুক্ত হয়েছে।",
}