export const labels = {
    booksPointer: "বুকস পয়েন্টার",
    books: "বইসমগ্র",
    welcomeMessage: "বুকস পয়েন্টারে আপনাকে স্বাগতম!",
    book: "বই",
    read: "পড়ুন...",
    reads: "পড়া হয়েছে",
    delete: "ডিলিট করুন",
    bookTitle: "বইয়ের নাম",
    startWriting: "লেখা শুরু করুন...",
    search: "খুঁজুন...",
    searchAuthor: "লেখক খুঁজুন...",
    searchCategory: "ধরণ খুঁজুন...",
    editProfile: "আপডেট প্রোফাইল",
    resetPassword: {
        header: "রিসেট পাসওয়ার্ড",
        heading: "আপনার পাসওয়ার্ড রিসেট করুন",
        currentPassword: "বর্তমান পাসওয়ার্ড",
        newPassword: "নতুন পাসওয়ার্ড",
        confirmPassword: "কনফার্ম পাসওয়ার্ড",
        submit: "রিসেট",
        success: "পাসওয়ার্ড সফলভাবে রিসেট হয়েছে।",
        error: "পাসওয়ার্ড রিসেট করতে সমস্যা হয়েছে। আবার চেষ্টা করুন।",
    },
    register: "রেজিস্টার করুন",
    firstName: "নামের প্রথম অংশ",
    lastName: "নামের শেষ অংশ",
    email: "ইমেইল",
    noAccount: "একাউন্ট নেই?",
    invalidEmail: "ইমেইলটি সঠিক হয়নি। সঠিক ইমেইল দিয়ে আবার চেষ্টা করুন।",
    passswordConfirmNotMatch: "পাসওয়ার্ড আর কনফার্ম পাসওয়ার্ডে মিল নেই।",
    invalidLogin: "ইমেইল অথবা পাসওয়ার্ড ভুল হয়েছ। আবার চেষ্টা করুন।",
    signIn: "লগইন",
    signOut: "লগআউট",
    editBook: "আপডেট করুন",
    privateBook: "প্রাইভেট করুন",
    publishBook: "পাবলিশ করুন",
    userRoleUser: "ব্যাবহারকারী",
    userRoleAuthor: "লেখক",
    userRolePublisher: "পাবলিশার",
    userDescription: "আপনার নিজের সম্পর্কে লিখুন...",
    userBookTypes: {
        books: "বইসমূহ",
        library: "লাইব্রেরী",
        // history: "ব্রাউজিং ইতিহাস",
        history: "ইতিহাস",
    },
    writeBook: "বই লিখুন",
    writeNewBook: "লিখুন",
    home: 'হোম', 
    author: 'লেখক',
    authors: 'লেখকগণ',
    selectAuthor: ' লেখক নির্বাচন করুন',
    audios: "অডিও বই",
    categories: 'ধরণ', 
    selectCategory: 'ধরণ নির্বাচন করুন',
    download: 'ডাউনলোড',
    downloadedAlready: 'ডাউনলোড হয়েছে',
    noBooksFound: "কোন বই পাওয়া যায়নি।",
    noBooksFoundForThisSeries: "এই সিরিজের জন্য কোন বই পাওয়া যায়নি।",
    deleteBook: "বইটি সফলভাবে মুছে ফেলা হয়েছে।",
    removingBookWarning: "বইটি মুছে ফেলতে যাচ্ছেন।",
    removeBookWarning: "এই বইটি মুছে ফেলতে চান?",
    pleaseLoginToContinue: "অগ্রসর হওয়ার জন্য অনুগ্রহ করে লগইন করুন।",
    bookCreate: {
        coverMessage: 'আপনি চাইলে একটি ছবিও যুক্ত করতে পারেন বইটির প্রচ্ছদ এর জন্য। (না দিলেও অসুবিধা নেই।)',
        title: 'বইটির নাম',
        titleRequired: 'বইয়ের নাম অবশ্যই লিখতে হবে।',
        category: 'বইটির ধরণ',
        categoryRequired: 'বইয়ের ধরণ অবশ্যই নির্বাচন করতে হবে।',
        author: 'বইটির লেখক',
        mainContent: 'মূল লেখা...',
        writeComplete: "লেখা সম্পন্ন হয়েছে।",
        bookExists: "বইটি ইতোমধ্যে বুকস পয়েন্টারে আছে।",
        viewBook: "দেখুন",
        preview: "preview",
        contentRequired: 'লেখা পাওয়া যায়নি।',
    },
    saveBookIntoDb: "বইটি সফলভাবে সেভ হয়েছে।",
    AddToLibrary: "লাইব্রেরীতে রাখুন",
    AddedToLibrary: "লাইব্রেরীতে আছে",
    saveBookIntoLibrary: "বইটি সফলভাবে লাইব্রেরীতে যুক্ত হয়েছে।",
    removedBookFromLibrary: "বইটি সফলভাবে লাইব্রেরী থেকে ডিলিট হয়েছে।",
    share: "শেয়ার",
    audioBook: "অডিও বই",
    audioBookNotAvailable: "অডিও বইটি এখনো উপলব্ধ নয়।",
    featureNotAvailable: "দুঃখিত, ডাউনলোদ সুবিধাটি এখনো যুক্ত করা হয়নি।",
    sorry: "দুঃখিত!",
    saveBook: "পোষ্ট করুন",
    reader: "পাঠক",
    publisher: 'পাবলিশার',
    totalReads: "মোট পড়া হয়েছে",
    totalPages: "মোট পৃষ্টা",
    readed: "পড়েছেন",
    user: {
        firstName: "নামের প্রথম অংশ",
        lastName: "নামের শেষ অংশ",
        email: "ইমেইল",
        phone: "ফোন নম্বর",
        totalBooks: "মোট বই",
        totalAudios: "মোট অডিও বই",
        page: "পৃষ্টা",
        totalDownloads: "মোট ডাউনলোড হয়েছে",
        totalLikes: "মোট লাইক হয়েছে",
        totalComments: "মোট মন্তব্য হয়েছে",
        totalFollowers: "মোট অনুসারী",
        totalFollowing: "মোট অনুসরণ",
        followers: "অনুসারী",
        following: "অনুসরণ",
        description: "ব্যক্তিগত বর্ণনা",
        editProfile: "প্রোফাইল আপডেট করুন",
        profileUpdated: "প্রোফাইল সফলভাবে আপডেট হয়েছে।",
        profileUpdateError: "প্রোফাইল আপডেট করতে সমস্যা হয়েছে। আবার চেষ্টা করুন।",
        followMe: "সাথে থাকুন",
        register: {
            firstName: "নতুন",
            lastName: "পাঠক",
        },
        update: {
            name: "নাম আপডেট করুন",
            email: "ইমেইল আপডেট করুন",
            updatePassword: "পাসওয়ার্ড আপডেট করুন",
            password: "পাসওয়ার্ড",
            confirmPassword: "কনফার্ম পাসওয়ার্ড",
            passwordLength: "পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।",
            passswordConfirmNotMatch: "পাসওয়ার্ড আর কনফার্ম পাসওয়ার্ডে মিল নেই।",
            phone: "ফোন নম্বর আপডেট করুন",
            description: "ব্যক্তিগত বর্ণনা আপডেট করুন",
            socials: "সোশ্যাল মিডিয়া লিঙ্ক আপডেট করুন",
        },
        socialMedia: {
            facebook: "ফেসবুক লিঙ্ক",
            twitter: "টুইটার লিঙ্ক",
            linkedin: "লিঙ্কডইন লিঙ্ক",
            instagram: "ইনস্টাগ্রাম লিঙ্ক",
            telegram: "টেলিগ্রাম লিঙ্ক",
            youtube: "ইউটিউব লিঙ্ক",
        },
        block: {
            you: "আপনি",
            blockUserButtonMessage: "কে ব্লক করছেন!",
            blockWarningStart: "আপনি কি নিশ্চিত যে আপনি ",
            blockWarningEnd: " কে ব্লক করতে চান? ব্লক করার পর আপনি আর তার কোন পোষ্ট দেখতে পাবেন না।",
            userBlockedMessage: "কে ব্লক হয়েছে।",
        }
    },
    createBook: {
        book: "বই",
        ethernelWord: "বাণী চিরন্তনী",
        song: "গান",
        joke: "কৌতুক",
        poem: "কাব্য ও কবিতা",
        selfAuthor: "আপনি নিজেই লেখক/লেখিকা"
    },
    newSeries: "নতুন সিরিজ",
    createNewSeries: "নতুন সিরিজ খুলুন.",
    seriesExists: "সিরিজ আছে। অন্য নামে তৈরি করতে পারেন!",
    sortWords: {
        yes: "হ্যাঁ।",
        no: "না"
    },
    deleteItem: {
        areYouSure: "আপনি কি নিশ্চিত?",
        removeFromLibrary: "আপনি এটি লাইব্রেরী থেকে মুছে ফেলতে চাইছেন।"
    },
    or: "অথবা",
    signInWithGoogle: "গুগলের মাধ্যমে লগইন করুন",
    notifications: "নোটিফিকেশন",
    noNotifications: "কোন নোটিফিকেশন নেই।",
    searhWriterBooks: "এর বইসমূহ খুঁজুন",
    signInLoading: "সাইন ইন হচ্ছে...",
    detailsScreenOfflineMessage: "আপনি অফলাইন, আপনার ডাটা কানেকশন ঠিক করুন।",
    loadingBook: "বই লোড হচ্ছে..., দয়া করে একটু অপেক্ষা করুন। এটি একটু সময় নিতে পারে।"
}

export default labels;