import { useSystemStore } from "../store/systemStore";

export const labelsBN = {
    booksPointer: "বুকস পয়েন্টার",
    books: "বইসমগ্র",
    welcomeMessage: "বুকস পয়েন্টারে আপনাকে স্বাগতম!",
    book: "বই",
    read: "পড়ুন...",
    reads: "পড়া হয়েছে",
    delete: "ডিলিট করুন",
    bookTitle: "বইয়ের নাম",
    startWriting: "লেখা শুরু করুন...",
    search: "খুঁজুন...",
    searchAuthor: "লেখক খুঁজুন...",
    searchCategory: "ধরণ খুঁজুন...",
    editProfile: "আপডেট প্রোফাইল",
    resetPassword: {
        header: "রিসেট পাসওয়ার্ড",
        heading: "আপনার পাসওয়ার্ড রিসেট করুন",
        currentPassword: "বর্তমান পাসওয়ার্ড",
        newPassword: "নতুন পাসওয়ার্ড",
        confirmPassword: "কনফার্ম পাসওয়ার্ড",
        submit: "রিসেট",
        success: "পাসওয়ার্ড সফলভাবে রিসেট হয়েছে।",
        error: "পাসওয়ার্ড রিসেট করতে সমস্যা হয়েছে। আবার চেষ্টা করুন।",
    },
    register: "রেজিস্টার করুন",
    firstName: "নামের প্রথম অংশ",
    lastName: "নামের শেষ অংশ",
    email: "ইমেইল",
    noAccount: "একাউন্ট নেই?",
    invalidEmail: "ইমেইলটি সঠিক হয়নি। সঠিক ইমেইল দিয়ে আবার চেষ্টা করুন।",
    passswordConfirmNotMatch: "পাসওয়ার্ড আর কনফার্ম পাসওয়ার্ডে মিল নেই।",
    invalidLogin: "ইমেইল অথবা পাসওয়ার্ড ভুল হয়েছ। আবার চেষ্টা করুন।",
    signIn: "লগইন",
    signOut: "লগআউট",
    editBook: "আপডেট করুন",
    privateBook: "প্রাইভেট করুন",
    publishBook: "পাবলিশ করুন",
    userRoleUser: "ব্যাবহারকারী",
    userRoleAuthor: "লেখক",
    userRolePublisher: "পাবলিশার",
    userDescription: "আপনার নিজের সম্পর্কে লিখুন...",
    userBookTypes: {
        books: "বইসমূহ",
        library: "লাইব্রেরী",
        // history: "ব্রাউজিং ইতিহাস",
        history: "ইতিহাস",
    },
    writeBook: "বই লিখুন",
    writeNewBook: "লিখুন",
    home: 'হোম', 
    author: 'লেখক',
    authors: 'লেখকগণ',
    selectAuthor: ' লেখক নির্বাচন করুন',
    audios: "অডিও বই",
    categories: 'ধরণ', 
    selectCategory: 'ধরণ নির্বাচন করুন',
    download: 'ডাউনলোড',
    downloadedAlready: 'ডাউনলোড হয়েছে',
    noBooksFound: "কোন বই পাওয়া যায়নি।",
    noBooksFoundForThisSeries: "এই সিরিজের জন্য কোন বই পাওয়া যায়নি।",
    deleteBook: "বইটি সফলভাবে মুছে ফেলা হয়েছে।",
    removingBookWarning: "বইটি মুছে ফেলতে যাচ্ছেন।",
    removeBookWarning: "এই বইটি মুছে ফেলতে চান?",
    pleaseLoginToContinue: "অগ্রসর হওয়ার জন্য অনুগ্রহ করে লগইন করুন।",
    bookCreate: {
        coverMessage: 'আপনি চাইলে একটি ছবিও যুক্ত করতে পারেন বইটির প্রচ্ছদ এর জন্য। (না দিলেও অসুবিধা নেই।)',
        title: 'বইটির নাম',
        titleRequired: 'বইয়ের নাম অবশ্যই লিখতে হবে।',
        category: 'বইটির ধরণ',
        categoryRequired: 'বইয়ের ধরণ অবশ্যই নির্বাচন করতে হবে।',
        author: 'বইটির লেখক',
        mainContent: 'মূল লেখা...',
        writeComplete: "লেখা সম্পন্ন হয়েছে।",
        bookExists: "বইটি ইতোমধ্যে বুকস পয়েন্টারে আছে।",
        viewBook: "দেখুন",
        preview: "preview",
        contentRequired: 'লেখা পাওয়া যায়নি।',
    },
    removeBook: "ডিলিট করুন!",
    removeLibraryBookWarning: "লাইব্রেরী থেকে বইটি মুছে ফেলতে চান?",
    saveBookIntoDb: "বইটি সফলভাবে সেভ হয়েছে।",
    AddToLibrary: "লাইব্রেরীতে রাখুন",
    AddedToLibrary: "লাইব্রেরীতে আছে",
    saveBookIntoLibrary: "বইটি সফলভাবে লাইব্রেরীতে যুক্ত হয়েছে।",
    removedBookFromLibrary: "বইটি সফলভাবে লাইব্রেরী থেকে ডিলিট হয়েছে।",
    share: "শেয়ার",
    audioBook: "অডিও বই",
    audioBookNotAvailable: "অডিও বইটি এখনো উপলব্ধ নয়।",
    featureNotAvailable: "দুঃখিত, ডাউনলোদ সুবিধাটি এখনো যুক্ত করা হয়নি।",
    sorry: "দুঃখিত!",
    saveBook: "পোষ্ট করুন",
    reader: "পাঠক",
    publisher: 'পাবলিশার',
    totalReads: "মোট পড়া হয়েছে",
    totalPages: "মোট পৃষ্টা",
    readed: "পড়েছেন",
    user: {
        firstName: "নামের প্রথম অংশ",
        lastName: "নামের শেষ অংশ",
        email: "ইমেইল",
        phone: "ফোন নম্বর",
        totalBooks: "মোট বই",
        totalAudios: "মোট অডিও বই",
        page: "পৃষ্টা",
        totalDownloads: "মোট ডাউনলোড হয়েছে",
        totalLikes: "মোট লাইক হয়েছে",
        totalComments: "মোট মন্তব্য হয়েছে",
        totalFollowers: "মোট অনুসারী",
        totalFollowing: "মোট অনুসরণ",
        followers: "অনুসারী",
        following: "অনুসরণ",
        description: "ব্যক্তিগত বর্ণনা",
        editProfile: "প্রোফাইল আপডেট করুন",
        profileUpdated: "প্রোফাইল সফলভাবে আপডেট হয়েছে।",
        profileUpdateError: "প্রোফাইল আপডেট করতে সমস্যা হয়েছে। আবার চেষ্টা করুন।",
        followMe: "সাথে থাকুন",
        register: {
            firstName: "নতুন",
            lastName: "পাঠক",
        },
        update: {
            name: "নাম আপডেট করুন",
            email: "ইমেইল আপডেট করুন",
            updatePassword: "পাসওয়ার্ড আপডেট করুন",
            password: "পাসওয়ার্ড",
            confirmPassword: "কনফার্ম পাসওয়ার্ড",
            passwordLength: "পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।",
            passswordConfirmNotMatch: "পাসওয়ার্ড আর কনফার্ম পাসওয়ার্ডে মিল নেই।",
            phone: "ফোন নম্বর আপডেট করুন",
            description: "ব্যক্তিগত বর্ণনা আপডেট করুন",
            socials: "সোশ্যাল মিডিয়া লিঙ্ক আপডেট করুন",
        },
        socialMedia: {
            facebook: "ফেসবুক লিঙ্ক",
            twitter: "টুইটার লিঙ্ক",
            linkedin: "লিঙ্কডইন লিঙ্ক",
            instagram: "ইনস্টাগ্রাম লিঙ্ক",
            telegram: "টেলিগ্রাম লিঙ্ক",
            youtube: "ইউটিউব লিঙ্ক",
        },
        block: {
            you: "আপনি",
            blockUserButtonMessage: "কে ব্লক করছেন!",
            blockWarningStart: "আপনি কি নিশ্চিত যে আপনি ",
            blockWarningEnd: " কে ব্লক করতে চান? ব্লক করার পর আপনি আর তার কোন পোষ্ট দেখতে পাবেন না।",
            userBlockedMessage: "কে ব্লক হয়েছে।",
            blockedUsers: "ব্লকেড ইউজার",
        },
        report: {
            reportingFor: "রিপোর্ট করছেন!"
        },
    },
    createBook: {
        book: "বই",
        ethernelWord: "বাণী চিরন্তনী",
        song: "গান",
        joke: "কৌতুক",
        poem: "কাব্য ও কবিতা",
        selfAuthor: "আপনি নিজেই লেখক/লেখিকা"
    },
    newSeries: "নতুন সিরিজ",
    createNewSeries: "নতুন সিরিজ খুলুন.",
    seriesExists: "সিরিজ আছে। অন্য নামে তৈরি করতে পারেন!",
    sortWords: {
        yes: "হ্যাঁ।",
        no: "না"
    },
    deleteItem: {
        areYouSure: "আপনি কি নিশ্চিত?",
        removeFromLibrary: "আপনি এটি লাইব্রেরী থেকে মুছে ফেলতে চাইছেন।",
        deleteMessage: "আপনি এটি ডিলিট করতে চাইছেন।"
    },
    or: "অথবা",
    signInWithGoogle: "গুগলের মাধ্যমে লগইন করুন",
    notifications: "নোটিফিকেশন",
    noNotifications: "কোন নোটিফিকেশন নেই।",
    searhWriterBooks: "এর বইসমূহ খুঁজুন",
    signInLoading: "সাইন ইন হচ্ছে...",
    detailsScreenOfflineMessage: "আপনি অফলাইন, আপনার ডাটা কানেকশন ঠিক করুন।",
    loadingBook: "বই লোড হচ্ছে..., দয়া করে একটু অপেক্ষা করুন। এটি একটু সময় নিতে পারে।",
    b: {
        readMore: 'আরও পড়ুন',
        readLess: 'কম পড়ুন'
    },
    visitSeries: "সিরিজ দেখুন",
    allBooks: "সকল বই",
    image: "ছবি",
    forYours: "আপনার জন্য",
    recomendedForYou: "বইসমূহঃ শুধুমাত্র আপনার জন্য",
    basedOnYourReadHistory: "আপনি ইতোমধ্যে যা পড়েছেন তার উপর ভিত্তি করে সাজানো",
    yourLibrary: "আপনার লাইব্রেরী",
    yourLibraryBooks: "আপনার যুক্ত করা বইসমূহ",
    seriesByThisAuthor: "এই লেখকের বইয়ের ধরণ সমূহ",
    userRoleLabel: "এই পাঠকের পাবলিশ করা বইয়ের ধরণ সমূহ",
    userSelfRoleLabel: "আপনার তৈরি করা ধরণ সমূহ",
    seeAllBooks: "সবগুলো বই দেখুন",
    viewSeries: "সিরিজ দেখুন",
    popularBooks: "জনপ্রিয় বইসমূহ",
    popularityByBp: "জনপ্রিয়তাঃ শুধুমাত্র বুকস পয়েন্টার অনুযায়ী (কোন জরিপের ফলাফল নয়)",
    readingComplete: "পড়েছেন",
    currentlyReading: "এখন পড়ছেন",
    currentlyReadingDescription: "যেসব বই পড়া শুরু করেছেন। কিন্তু শেষ করেননি।",
    resentActivity: "রিসেন্ট এক্টিভিটি",
    review: "রিভিউ",
    noReview: "কোন রিভিউ নেই",
    countReview: " টি রিভিউ",
    readStatus: {
        readed: "পৃষ্টা পড়েছেন, ",
        inTotal: "মোট",
        inTotalPages: "পৃষ্টার মধ্যে।",
        nothingComplete: "কিছুই পড়ে শেষ করেননি এখনো"
    },
    change: "পরিবর্তন করুন",
    noAuthorFound: "কোন লেখক পাওয়া যায়নি।",
    writeReview: "রিভিউ লিখুন",
    seeReviews: "রিভিউ দেখুন",
    writeReply: "রিপ্লাই লিখুন",
    postedAt: "পোস্ট করা হয়েছে: ",
    userNotFound: "কোন ইউজার পাওয়া যায়নি।",
    visitedUserNotFound: "দুঃখিত, ইউজার সম্পর্কে কোন তথ্য পাওয়া যায়নি।",
    onlyForDownloadedBooks: "শুধুমাত্র ডাউনলোড করা বই ইন্টারনেট ছাড়া পড়া যাবে।",
    edit: "এডিট করুন",
    bookNotFound: "কোন বই পাওয়া যায়নি।",
    relatedBooks: "এই রকমের আরও কিছু বই",
    versionUpdate: "নতুন ভার্সন পাওয়া যাচ্ছে। নতুন ভার্সনে নতুন ফিচার যোগ করা হয়েছে। এবং কিছু সমস্যার সমাধান করা হয়েছে। ব্যবহারে আরও ভাল সুবিধা পেতে আপডেট করুন।",
    textEditor: "ডায়েরি",
    selectSeriesIfYouWant: "সিরিজ নির্বাচন করুন (যদি আপনি এই বইটি কোন সিরিজের মধ্যে যুক্ত করতে চান)",
    tryAgain: "আবার চেষ্টা করুন",
    report: "রিপোর্ট করুন (Report)",
    block: "ব্লক করুন (Block)",
    readBanglaBooks: "বাংলা বইসমূহ পড়ুন",
    readEnglishBooks: "Read English Books",
    authorNoDescription: "লেখকের সম্পর্কে কোন তথ্য নেই।"
}

export const labelsEN = {
    booksPointer: "Books Pointer",
    books: "Books",
    welcomeMessage: "Welcome to Books Pointer!",
    book: "Book",
    read: "Read...",
    reads: "Read",
    delete: "Delete",
    bookTitle: "Book Title",
    startWriting: "Start writing...",
    search: "Search...",
    searchAuthor: "Search author...",
    searchCategory: "Search category...",
    editProfile: "Update Profile",
    resetPassword: {
        header: "Reset Password",
        heading: "Reset your password",
        currentPassword: "Current Password",
        newPassword: "New Password",
        confirmPassword: "Confirm Password",
        submit: "Reset",
        success: "Password has been reset successfully.",
        error: "There was a problem resetting the password. Please try again.",
    },
    register: "Register",
    firstName: "First Name",
    lastName: "Last Name",
    email: "Email",
    noAccount: "No account?",
    invalidEmail: "The email is invalid. Please try again with a valid email.",
    passswordConfirmNotMatch: "Password and confirm password do not match.",
    invalidLogin: "Email or password is incorrect. Please try again.",
    signIn: "Sign In",
    signOut: "Sign Out",
    editBook: "Update",
    privateBook: "Make Private",
    publishBook: "Publish",
    userRoleUser: "User",
    userRoleAuthor: "Author",
    userRolePublisher: "Publisher",
    userDescription: "Write about yourself...",
    userBookTypes: {
        books: "Books",
        library: "Library",
        history: "History",
    },
    writeBook: "Write Book",
    writeNewBook: "Write",
    home: "Home",
    author: "Author",
    authors: "Authors",
    selectAuthor: "Select Author",
    audios: "Audio Books",
    categories: "Categories",
    selectCategory: "Select Category",
    download: "Download",
    downloadedAlready: "Already Downloaded",
    noBooksFound: "No books found.",
    noBooksFoundForThisSeries: "No books found for this series.",
    deleteBook: "The book has been deleted successfully.",
    removingBookWarning: "You are about to delete the book.",
    removeBookWarning: "Do you want to delete this book?",
    pleaseLoginToContinue: "Please log in to continue.",
    bookCreate: {
        coverMessage: "You can add an image as the book cover if you want. (It is okay if you do not.)",
        title: "Book Title",
        titleRequired: "Book title is required.",
        category: "Book Category",
        categoryRequired: "Book category must be selected.",
        author: "Book Author",
        mainContent: "Main content...",
        writeComplete: "Writing completed.",
        bookExists: "This book already exists in Books Pointer.",
        viewBook: "View",
        preview: "Preview",
        contentRequired: "No content found.",
    },
    removeBook: "Delete!",
    removeLibraryBookWarning: "Do you want to remove this book from the library?",
    saveBookIntoDb: "The book has been saved successfully.",
    AddToLibrary: "Add to Library",
    AddedToLibrary: "In Library",
    saveBookIntoLibrary: "The book has been added to the library successfully.",
    removedBookFromLibrary: "The book has been deleted from the library successfully.",
    share: "Share",
    audioBook: "Audio Book",
    audioBookNotAvailable: "This audio book is not available yet.",
    featureNotAvailable: "Sorry, the download feature has not been added yet.",
    sorry: "Sorry!",
    saveBook: "Post",
    reader: "Reader",
    publisher: "Publisher",
    totalReads: "Total Reads",
    totalPages: "Total Pages",
    readed: "Read",
    user: {
        firstName: "First Name",
        lastName: "Last Name",
        email: "Email",
        phone: "Phone Number",
        totalBooks: "Total Books",
        totalAudios: "Total Audio Books",
        page: "Page",
        totalDownloads: "Total Downloads",
        totalLikes: "Total Likes",
        totalComments: "Total Comments",
        totalFollowers: "Total Followers",
        totalFollowing: "Total Following",
        followers: "Followers",
        following: "Following",
        description: "Personal Description",
        editProfile: "Update Profile",
        profileUpdated: "Profile updated successfully.",
        profileUpdateError: "There was a problem updating the profile. Please try again.",
        followMe: "Follow",
        register: {
            firstName: "New",
            lastName: "Reader",
        },
        update: {
            name: "Update Name",
            email: "Update Email",
            updatePassword: "Update Password",
            password: "Password",
            confirmPassword: "Confirm Password",
            passwordLength: "Password must be at least 6 characters long.",
            passswordConfirmNotMatch: "Password and confirm password do not match.",
            phone: "Update Phone Number",
            description: "Update Personal Description",
            socials: "Update Social Media Links",
        },
        socialMedia: {
            facebook: "Facebook Link",
            twitter: "Twitter Link",
            linkedin: "LinkedIn Link",
            instagram: "Instagram Link",
            telegram: "Telegram Link",
            youtube: "YouTube Link",
        },
        block: {
            you: "You",
            blockUserButtonMessage: "to block!",
            blockWarningStart: "Are you sure you want to block ",
            blockWarningEnd: "? After blocking, you will no longer be able to see any of their posts.",
            userBlockedMessage: "has been blocked.",
            blockedUsers: "Blocked Users",
        },
        report: {
            reportingFor: "Reporting for!"
        },
    },
    createBook: {
        book: "Book",
        ethernelWord: "Eternal Words",
        song: "Song",
        joke: "Joke",
        poem: "Poetry and Poems",
        selfAuthor: "You are the author"
    },
    newSeries: "New Series",
    createNewSeries: "Create a new series.",
    seriesExists: "Series already exists. You can create one with another name!",
    sortWords: {
        yes: "Yes.",
        no: "No"
    },
    deleteItem: {
        areYouSure: "Are you sure?",
        removeFromLibrary: "You are trying to remove this from the library.",
        deleteMessage: "You are trying to delete this."
    },
    or: "Or",
    signInWithGoogle: "Sign in with Google",
    notifications: "Notifications",
    noNotifications: "No notifications.",
    searhWriterBooks: "Search their books",
    signInLoading: "Signing in...",
    detailsScreenOfflineMessage: "You are offline, please fix your data connection.",
    loadingBook: "Loading book..., please wait a moment. This may take some time.",
    b: {
        readMore: "Read more",
        readLess: "Read less"
    },
    visitSeries: "Visit Series",
    allBooks: "All Books",
    image: "Image",
    forYours: "For You",
    recomendedForYou: "Books: only for you",
    basedOnYourReadHistory: "Organized based on what you have already read",
    yourLibrary: "Your Library",
    yourLibraryBooks: "Books you added",
    seriesByThisAuthor: "Book categories by this author",
    userRoleLabel: "Categories of books published by this reader",
    userSelfRoleLabel: "Categories created by you",
    seeAllBooks: "See All Books",
    viewSeries: "View Series",
    popularBooks: "Popular Books",
    popularityByBp: "Popularity: only according to Books Pointer (not the result of any survey)",
    readingComplete: "Read",
    currentlyReading: "Currently Reading",
    currentlyReadingDescription: "Books you started reading but have not finished.",
    resentActivity: "Recent Activity",
    review: "Review",
    noReview: "No reviews",
    countReview: " reviews",
    readStatus: {
        readed: "pages read, ",
        inTotal: "out of",
        inTotalPages: "pages.",
        nothingComplete: "You have not finished reading anything yet"
    },
    change: "Change",
    noAuthorFound: "No author found.",
    writeReview: "Write Review",
    seeReviews: "See Reviews",
    writeReply: "Write Reply",
    postedAt: "Posted at: ",
    userNotFound: "No user found.",
    visitedUserNotFound: "Sorry, no information was found about the user.",
    onlyForDownloadedBooks: "Only downloaded books can be read without internet.",
    edit: "Edit",
    bookNotFound: "No book found.",
    relatedBooks: "More books like this",
    versionUpdate: "A new version is available. New features have been added and some issues have been fixed. Update for a better experience.",
    textEditor: "Diary",
    selectSeriesIfYouWant: "Select a series (if you want to add this book to a series)",
    tryAgain: "Try again",
    report: "Report",
    block: "Block",
    readBanglaBooks: "বাংলা বইসমূহ পড়ুন",
    readEnglishBooks: "Read English Books",
    authorNoDescription: "No information about the author."
}
export const getLabels = (lang: string) => lang === 'bn' ? labelsBN : labelsEN;

export const useLabels = () => {
    const lang = useSystemStore((state) => state.lang);
    return getLabels(lang);
};

export const labels = new Proxy(labelsEN, {
    get(_, prop: keyof typeof labelsEN) {
        return getLabels(useSystemStore.getState().lang)[prop];
    },
});

export default labels;
