import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  // container: { flex: 1, backgroundColor: '#F5F7FB', height: '94%', marginBottom: 40 },
  container: { flex: 1, backgroundColor: '#F8FAFC' },
  header: {
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: '#6D28D9',
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButton: { padding: 5, marginRight: 7 },
  statusDot: {
    width: 40,
    height: 40,
    borderRadius: 25,
    backgroundColor: '#55efc4',
    marginRight: 12,
  },
  headerTitle: { color: '#FFF', fontSize: 17, fontWeight: '700' },
  headerSubtitle: { color: 'rgba(255,255,255,0.75)', fontSize: 12, marginLeft: 5 },
  headerOnlineDot: { width: 7, height: 7, borderRadius: 4 },
  listContent: { paddingHorizontal: 14, paddingTop: 14, paddingBottom: 18 },
  messageBubble: {
    paddingLeft: 12,
    paddingRight: 7,
    paddingVertical: 8,
    borderRadius: 18,
    marginBottom: 8,
    maxWidth: '84%',
  },
  myMessage: {
    alignSelf: 'flex-end',
    backgroundColor: '#7C3AED',
    borderBottomRightRadius: 2,
  },
  theirMessage: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFF',
    borderBottomLeftRadius: 4,
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  myText: { color: '#FFF', fontSize: 15, lineHeight: 21, paddingBottom: 2, marginRight: 5 },
  theirText: { color: '#1E293B', fontSize: 15, lineHeight: 21 },
  timestamp: {
    fontSize: 10,
    color: 'rgba(255,255,255,0.7)',
    marginTop: 4,
    alignSelf: 'flex-end',
  },
  thereTimestamp: {
    fontSize: 10,
    color: 'rgba(0,0,0,0.4)',
    marginTop: 4,
    alignSelf: 'flex-start',
  },
  inputContainer: {
    flexDirection: 'row',
    paddingHorizontal: 5,
    alignItems: 'flex-end',
    paddingVertical: 7,
    backgroundColor: '#FFF',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#E2E8F0',
  },
  input: {
    flex: 1,
    minHeight: 42,
    maxHeight: 120,
    borderRadius: 21,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: '#F1F5F9',
    marginRight: 5,
    fontSize: 15,
    color: '#000',
  },
  sendButton: { width: 42, height: 42, alignItems: 'center', justifyContent: 'center', marginLeft: 5, borderRadius: 21, backgroundColor: '#7C3AED' },
  sendButtonDisabled: { backgroundColor: '#CBD5E1' },
  sendButtonText: { color: '#FFF', fontWeight: 'bold' },

  // reply
  replyPreviewContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#f9f9f9', // Slightly off-white
    borderTopWidth: 1,
    borderTopColor: '#eee',
    borderLeftWidth: 4,
    borderLeftColor: '#7C3AED',
  },
  replyPreviewContent: {
    flex: 1,
    paddingLeft: 8,
  },
  replyPreviewTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#6D28D9',
  },
  replyPreviewText: {
    fontSize: 14,
    color: '#666',
  },
  closeReplyButton: {
    padding: 4,
  },
  replyBarAccent: {
    width: 4,
    height: 24,
    backgroundColor: '#7C3AED',
    marginRight: 8,
  },
  emptyMessages: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingBottom: 80 },
  emptyTitle: { color: '#334155', fontSize: 16, fontWeight: '700', marginTop: 10 },
  muted: { color: '#94A3B8', fontSize: 13, marginTop: 6 },
  editPreview: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 16, paddingVertical: 8, backgroundColor: '#F5F3FF', borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#DDD6FE' },
  editText: { flex: 1, color: '#6D28D9', fontSize: 13, fontWeight: '600' },
  fallback: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 28 },
  fallbackTitle: { color: '#334155', fontSize: 18, fontWeight: '700' },
  fallbackText: { color: '#64748B', marginTop: 8 },
  fallbackButton: { marginTop: 20, paddingHorizontal: 20, paddingVertical: 11, borderRadius: 20, backgroundColor: '#7C3AED' },
  fallbackButtonText: { color: '#FFF', fontWeight: '700' },
});
